# Generated by Django 4.2.5 on 2023-09-09 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rows', models.IntegerField()),
                ('cols', models.IntegerField()),
                ('data', models.JSONField()),
            ],
            options={
                'db_table': 'Matrix',
            },
        ),
    ]
